language: python
matrix:
    include:
        - python: 3.9
          dist: bionic
          sudo: true
        - python: 3.9
          arch: arm64
          dist: bionic
          sudo: true

before_install:
    - pip install poetry

install:
    - poetry install

script:
    - tox
